source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'CrossoverTest' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'GCDWebServer', '~> 3.0'
    pod 'RealmSwift'
end

target 'CrossoverTestTests' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'GCDWebServer', '~> 3.0'
    pod 'RealmSwift'
end
