source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Jitensha' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'RealmSwift'
    pod 'GoogleMaps'
end

target 'JitenshaTests' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'RealmSwift'
    pod 'GoogleMaps'
end
